name: Flutter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          flutter-version: '3.10.x' # Specify the desired Flutter version
          channel: 'stable' # Specify the Flutter channel
      
      - name: Flutter Doctor
        run: flutter -v doctor
        
      - name: Get packages
        run: flutter -v pub get

      - name: Run tests
        run: flutter test
